Odometer
DIT112-V21/group-17 pull request #174
Opened 2021-07-30 15:29 UTC by guscuizi

Adding funtion:  transfer the odometer data  from smart car to Android APP, and display it.

2021-07-30 16:18 UTC, platisd requested changes
Please address the comments I left and add screenshots of the new functionality in the pull request body.

2021-07-30 16:18 UTC, platisd commented on android/app/src/main/java/smart/delirover/app/MailmanTraveledDistanceActivity.java
> +//MQTT connection part of the code is built on https://github.com/DIT112-V21/smartcar-mqtt-controller.git
An MQTT client [already exists](https://github.com/DIT112-V21/group-17/blob/master/android/app/src/main/java/smart/delirover/app/MqttClient.java), please reuse that.

2021-07-30 16:18 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +        if (currentTime - previousFrame >= oneSecond) {
By doing this, your camera feed frame rate became 15 times slower. I don't see any good reason why it should be like that. Please revise.

2021-07-30 16:18 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +		  mqtt.publish("/smartcar/ultrasound/front", distance);
Please indent the code appropriately. You can easily do this by pressing "Ctrl + T" on the Arduino IDE.

2021-07-30 16:18 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +      }
Commented out code is a code-smell. If you don't need it, remove it.

2021-07-30 16:18 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +      return leftOdometer.getDistance();
Why only from the left odometer and not from both? The `DistanceCar` class (and therefore the `SmartCar` one too) has a function just for that.

2021-07-30 16:19 UTC, platisd commented on android/app/src/main/AndroidManifest.xml
> +    tools:ignore="MissingLeanbackLauncher">
What is `MissingLeanbackLauncher` and why should it be ignored?

2021-08-01 07:37 UTC, platisd commented
> guscuizi requested a review from platisd

I've already left my review. Please address the comments.

2021-08-02 05:47 UTC, guscuizi commented
Hi,

I added this code by mistake, just delete it, it won’t affect the software function.
I will also delete it, in the project.

Sincerely,
Zizhuang Cui
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dimitris Platis ***@***.***>
发送时间: Saturday, July 31, 2021 12:20:09 AM
收件人: DIT112-V21/group-17 ***@***.***>
抄送: guscuizi ***@***.***>; Author ***@***.***>
主题: Re: [DIT112-V21/group-17] Odometer (#174)


@platisd commented on this pull request.

________________________________

In android/app/src/main/AndroidManifest.xml<https://github.com/DIT112-V21/group-17/pull/174#discussion_r680053118>:

> @@ -1,7 +1,8 @@
 <?xml version="1.0" encoding="utf-8"?>
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:tools="http://schemas.android.com/tools"
-    package="com.delirover.app">
+    package="com.delirover.app"
+    tools:ignore="MissingLeanbackLauncher">


What is MissingLeanbackLauncher and why should it be ignored?

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/DIT112-V21/group-17/pull/174#pullrequestreview-719267697>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATMHVNGEFTPKUEXDUWBN7E3T2LGLTANCNFSM5BIX2FPQ>.

2021-08-02 06:21 UTC, platisd commented
> I added this code by mistake, just delete it, it won’t affect the software function.
I will also delete it, in the project.

First of all, I don't understand what code you are referring to. Please go to the [pull request on GitHub](https://github.com/DIT112-V21/group-17/pull/174) and respond to the comments there.
Secondly, this is a code review for **you** to fix the problems, not me. This is a process you should have already been familiar with...

2021-08-02 07:18 UTC, merged

2021-08-02 08:13 UTC, platisd commented
Create another pull request towards the `master` branch so it can be properly reviewed please...

2021-08-02 09:11 UTC, platisd commented on android/app/src/main/java/smart/delirover/app/MailmanTraveledDistanceActivity.java
> +    // I'm unfamilar with reusing the MqttClient, so I have no choice but to keep the code as it is.
You already copy pasted the MqttClient, so it's difficult to see how "you have no choice" to reuse it. Please reuse it and don't respond with code comments to pull request review comments.

2021-08-03 15:24 UTC, guscuizi commented
Okay, I will do this, thank you for your patience.

Sincerely，
ZiZhuang Cui
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dimitris Platis ***@***.***>
发送时间: Monday, August 2, 2021 4:13:26 PM
收件人: DIT112-V21/group-17 ***@***.***>
抄送: guscuizi ***@***.***>; State change ***@***.***>
主题: Re: [DIT112-V21/group-17] Odometer (#174)


Create another pull request towards the master branch so it can be properly reviewed please...

―
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/DIT112-V21/group-17/pull/174#issuecomment-890819523>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATMHVNATB3ZCFIB33XCCPWDT2ZHSNANCNFSM5BIX2FPQ>.