Obstacle avoidance
DIT112-V21/group-17 pull request #20
Opened 2021-04-09 16:01 UTC by sjoblads

The car moves forward until it detects an object and stops

2021-04-09 16:17 UTC, platisd requested changes

2021-04-09 16:17 UTC, platisd commented on arduino/smartcar/smartcar.ino
> +    if (front.getDistance() != 0 && front.getDistance()< 200)
You are conducting **two** measurements that may well return different results. If for example the first call return `300` and the second one `0` you will stop the car even though the obstacle would be very far away

2021-04-12 19:24 UTC, platisd approved these changes

2021-04-12 19:49 UTC, MaabMohammedali approved these changes

2021-04-12 19:49 UTC, merged